import { MigrationInterface, QueryRunner } from 'typeorm';

export class IntegrationCategorySeeders1727795115929
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            INSERT INTO public.integration 
                (application_id, application_name, application_description, application_icon, provider_name, provider_link, total_installs, categories, features, languages, requirement_permissions, subscription_title, subscriptions, subscription_link, sort, "type")
            VALUES
                ('google-calendar', 'Google Calendar', 'Book meetings quickly and easily with CustomerCity and Google Calendar.', 'https://cdn-icons-png.flaticon.com/128/2702/2702609.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Productivity}', '{"Contact Management","Content Management",Templates}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, and Dutch', NULL, 'Gmail Subscription', 'Free, Basic, or Business plans', 'https://workspace.google.com/intl/en_id/pricing.html', 0, 'user'),
                ('demandbase', 'Demandbase', 'A B2B marketing platform offering account-based marketing solutions with data and targeting tools to identify and engage potential customers.', 'https://avatars.slack-edge.com/2022-02-10/3075346230167_183c0cc04f33023a06b8_512.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{"Data Provider"}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Demandbase Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.demandbase.com/pricing/', 0, 'user'),
                ('hubspot', 'HubSpot', 'A comprehensive platform offering marketing, sales, and customer service tools to help businesses attract visitors, convert leads, and close customers.', 'https://logowik.com/content/uploads/images/hubspot5453.logowik.com.webp', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Marketing}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'HubSpot Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.hubspot.com/pricing/marketing/enterprise?term=annual', 0, 'user'),
                ('gmail', 'Gmail', 'Bring CustomerCity to your inbox with the CustomerCity integration for Gmail.', 'https://cdn-icons-png.flaticon.com/128/281/281769.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Productivity}', '{"Contact Management","Content Management",Templates}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, and Dutch', NULL, 'Gmail Subscription', 'Free, Basic, or Business plans', 'https://workspace.google.com/intl/en_id/pricing.html', 0, 'user'),
                ('marketo', 'Marketo', 'Marketing automation software that enables companies to engage customers and prospects through email, mobile, social media, digital ads, and more.', 'https://cdn.iconscout.com/icon/free/png-256/free-marketo-logo-icon-download-in-svg-png-gif-file-formats--technology-social-media-vol-1-pack-logos-icons-3030046.png?f=webp&w=256', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Marketing}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Marketo Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.vertice.one/pricing', 0, 'user'),
                ('eloqua', 'Eloqua', 'An enterprise-level marketing automation platform by Oracle, designed for complex marketing campaigns and lead nurturing.', 'https://logodix.com/logo/2081529.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Marketing}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Eloqua Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://crozdesk.com/software/eloqua/pricing', 0, 'user'),
                ('zoominfo', 'ZoomInfo', 'A sales intelligence platform providing comprehensive B2B contact and company data to help sales and marketing teams identify and connect with prospects.', 'https://th.bing.com/th/id/OIP.OfZrwuwN7NOBbktER4RLVwAAAA?rs=1&pid=ImgDetMain', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{"Data Provider"}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'ZoomInfo Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://lp.lusha.com/prospecting-competitors-v6-zoominfo/?v=pricing-pays&utm_source=bing&utm_medium=cpc&utm_campaign=438207826&utm_content=1141294806900724-&utm_term=zoominfo%20pricing_e_kwd-71331622770486:loc-175&msclkid=3bf8276d384b15e6b474419b910f441c', 0, 'user'),
                ('apollo.io', 'Apollo.io', 'A data-driven sales platform offering contact data, engagement tools, and analytics to streamline prospecting and outreach.', 'https://www.paraform.com/apollo_logo.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{"Data Provider"}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Apollo.io Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.apollo.io/pricing?gad_source=1&gclid=Cj0KCQjwr9m3BhDHARIsANut04YB3X4BxVhKH4HHaSeH7n5ibTYLJgddxmIxbaBbQJCpu3r-xF1zXcMaAuT0EALw_wcB', 0, 'user'),
                ('clearbit', 'Clearbit', 'A marketing data engine that helps businesses find prospects, enrich customer profiles, and improve data accuracy for better marketing and sales.', 'https://capacity.com/wp-content/uploads/2021/02/clearbit.png.webp', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{"Data Provider"}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Clearbit Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.cognism.com/clearbit-pricing', 0, 'user'),
                ('outreach', 'Outreach', 'A sales engagement platform that automates and streamlines communication workflows, helping sales teams improve efficiency and close more deals.', 'https://a.storyblok.com/f/157376/192x192/7e7c13a76b/outreach_2x.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Sales}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Outreach Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.outreach.io/pricing#view-packages', 0, 'user'),
                ('salesloft', 'Salesloft', 'Provides tools for cadence automation, email tracking, and analytics to help sales reps connect with prospects and enhance their sales processes.', 'https://cdn.prod.website-files.com/6640cd28f51f13175e577c05/664e00bd1334eea794945d86_411538f3-3c7a-5dd9-a6b4-0c8a3fc786f9.svg', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Sales}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Salesloft Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.salesloft.com/pricing', 0, 'user'),
                ('freshworks', 'Freshworks', 'Offers a suite of products including Freshsales CRM, which helps businesses manage customer relationships and sales pipelines effectively.', 'https://companieslogo.com/img/orig/FRSH-03da94b4.png?t=1720244491', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{CRM}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Freshworks Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.freshworks.com/crm/pricing/?msclkid=caaaaafb578e1655654ecc0de6d3a54c&utm_source=bing&utm_medium=FSales-InsideEU-Search-EU-Brand&utm_campaign=FSales-InsideEU-Search-EU-Brand&utm_term=freshworks%20crm%20pricing&device=c&matchtype=p&network=o&gclid=&msclkid=caaaaafb578e1655654ecc0de6d3a54c', 0, 'user'),
                ('stripe', 'Stripe', 'An online payment processing platform that enables businesses to accept payments, send payouts, and manage their online transactions securely.', 'https://cdn.icon-icons.com/icons2/2699/PNG/512/stripe_logo_icon_167962.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Accounting}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Stripe Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://stripe.com/en-ch/pricing', 0, 'user'),
                ('linkedin-sales-navigator', 'LinkedIn Sales Navigator', 'A LinkedIn tool that helps sales professionals target the right prospects, understand key insights, and engage with personalized outreach.', 'https://cdn1.iconfinder.com/data/icons/logotypes/32/circle-linkedin-512.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Sales}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'LinkedIn Sales Navigator Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://business.linkedin.com/sales-solutions/compare-plans', 0, 'user'),
                ('ms-dynamics-365', 'MS Dynamics 365', 'A set of intelligent business applications including CRM and ERP solutions to manage customer relationships, finances, and operations.', 'https://logolook.net/wp-content/uploads/2022/10/Dynamics-365-Emblem.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{CRM}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'MS Dynamics 365 Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.microsoft.com/en/dynamics-365/pricing-overview?msockid=1b550d63f3a6669a05f0194ff24b67f1', 0, 'user'),
                ('zoho-crm', 'Zoho CRM', 'A cloud-based CRM platform that helps businesses manage sales, marketing, contacts, customer support, and inventory management in a single system.', 'https://media.licdn.com/dms/image/v2/D5633AQFaED_j5-8vAA/productpage-logo-image_200_200/productpage-logo-image_200_200/0/1690388526759/bilzy_tech_zoho_crm_logo?e=1728054000&v=beta&t=912NpCMxmy_h-ZhKechKw6j27BSG3GZ3SqBKzXD6nNU', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{CRM}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Zoho CRM Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.zoho.com/crm/zohocrm-pricing.html', 0, 'user'),
                ('mysql', 'MySQL', 'An open-source relational database management system widely used for web applications and services.', 'https://1000logos.net/wp-content/uploads/2020/08/MySQL-Logo-500x313.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Database}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'MySQL Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.mysql.com/products/', 0, 'user'),
                ('oracle-database', 'Oracle Database', 'An enterprise-grade, multi-model database management system designed for high-performance and secure data management.', 'https://m.media-amazon.com/images/I/41QodfboFdL.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Database}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Oracle Database Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.oracle.com/database/base-database-service/pricing/', 0, 'user'),
                ('snowflake', 'Snowflake', 'A cloud-based data warehousing platform offering data storage, processing, and analytics solutions that are fast and easy to use.', 'https://companieslogo.com/img/orig/SNOW-35164165.png?t=1720244494', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Database}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Snowflake Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.snowflake.com/en/data-cloud/pricing-options/', 0, 'user'),
                ('gainsight', 'Gainsight', 'A customer success platform that helps businesses reduce churn, drive upsell, and improve customer satisfaction through data-driven insights.', 'https://www.guidecx.com/nitropack_static/vBklnuPDePsLiszpEmvbyPEwIqQemANF/assets/images/optimized/rev-14c6179/www.guidecx.com/wp-content/uploads/2023/08/Gainsight-Icon-Website-1.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Support}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Gainsight Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://essentials.gainsight.com/solutions/pricing/', 0, 'user'),
                ('intercom', 'Intercom', 'A customer communication platform offering messaging services, chatbots, and engagement tools for sales, marketing, and support teams.', 'https://cdn.worldvectorlogo.com/logos/intercom-2.svg', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Support}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Intercom Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.intercom.com/pricing/calculator', 0, 'user'),
                ('zendesk', 'Zendesk', 'A customer service and engagement platform providing support, sales, and customer engagement software for businesses.', 'https://cdn.icon-icons.com/icons2/2429/PNG/512/zendesk_logo_icon_147198.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Support}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Zendesk Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.zendesk.com/pricing/', 0, 'user'),
                ('slack', 'Slack', 'A channel-based messaging platform that facilitates real-time communication and collaboration among team members.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Slack_icon_2019.svg/127px-Slack_icon_2019.svg.png?20200128081203', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Productivity}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Slack Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://app.slack.com/plans/T01R25ESW0H?geocode=en-gb&cdn_fallback=1&force_cold_boot=1', 0, 'user'),
                ('postgresql', 'PostgreSQL', 'A powerful, open-source object-relational database system with a strong reputation for reliability and data integrity.', 'https://cdn.icon-icons.com/icons2/2699/PNG/512/postgresql_src_logo_icon_170834.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Database}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'PostgreSQL Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.postgresql.org/about/licence/', 0, 'user'),
                ('aws-dynamodb', 'AWS DynamoDB', 'A fully managed NoSQL database service by AWS that provides fast and predictable performance with seamless scalability.', 'https://scalefactory.com/blog/2022/01/18/a-decade-of-dynamodb/img/dynamodb_2012.svg', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Database}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'AWS DynamoDB Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://aws.amazon.com/dynamodb/pricing/?nc1=h_ls', 0, 'user'),
                ('ms-sql-azure', 'MS SQL Azure', 'A fully managed relational cloud database service built on Microsoft SQL Server technologies, offering scalability and high availability.', 'https://estuary.dev/static/d02a8d0785a4d9eeddead9dcc720f436/bbe3c/569dae_Azure_Sql_Server_Logo_Transparent_1_13b0b548d9.webp', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Database}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'MS SQL Azure Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://azure.microsoft.com/en-us/pricing/details/azure-sql-managed-instance/single/', 0, 'user'),
                ('aws-s3', 'AWS S3', 'Amazon Simple Storage Service, an object storage service offering scalability, data availability, security, and performance.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Amazon-S3-Logo.svg/428px-Amazon-S3-Logo.svg.png?20220427001138', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Database}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'AWS S3 Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://aws.amazon.com/s3/pricing/', 0, 'user'),
                ('chargebee', 'Chargebee', 'A subscription billing and revenue management platform that automates recurring billing, invoicing, and revenue recognition for subscription-based businesses.', 'https://logosandtypes.com/wp-content/uploads/2020/06/chargebee-old.svg', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Accounting}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Chargebee Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.chargebee.com/pricing/', 0, 'user'),
                ('microsoft-teams', 'Microsoft Teams', 'A collaboration platform combining chat, video meetings, file storage, and app integration to enhance team communication and productivity.', 'https://cdn0.iconfinder.com/data/icons/logos-microsoft-office-365/128/Microsoft_Office-10-512.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Productivity}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Microsoft Teams Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.microsoft.com/en-us/microsoft-teams/teams-products?msockid=1b550d63f3a6669a05f0194ff24b67f1', 0, 'user'),
                ('pipedrive', 'Pipedrive', 'A sales-focused CRM designed to help small to medium-sized businesses manage leads, track communications, and automate sales processes.', 'https://cdn.prod.website-files.com/61702af2e3966e09c4101538/666c94db405a4574648dbcb9_6404bff5-b838-56c7-a570-947e0d5a2d5f.svg', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{CRM}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Pipedrive Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.pipedrive.com/en/gettingstarted?utm_source=bing&utm_medium=cpc&utm_campaign=CH_EN_Brd_All&utm_content=Price&utm_term=pipedrive%20pricing&cid=568393241&aid=1179777734959735&tid=kwd-73736403776205:loc-3322&msclkid=5207c4616e65124de7a3a297df5efc72', 0, 'user'),
                ('xero', 'Xero', 'Online accounting software providing tools for invoicing, bank reconciliation, bookkeeping, and financial reporting for small businesses.', 'https://cdn.iconscout.com/icon/free/png-512/free-xero-logo-icon-download-in-svg-png-gif-file-formats--technology-social-media-company-vol-7-pack-logos-icons-2945240.png?f=webp&w=256', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Accounting}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, Dutch', NULL, 'Xero Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.xero.com/pricing-plans/', 0, 'user'),
                ('office365', 'Office 365', 'Analyze your Office 365 data and discover insights with CustomerCity', 'https://cdn-icons-png.flaticon.com/128/732/732221.png', 'CustomerCity', 'https://customercitydev.com', '15,000+', '{Productivity}', '{"Contact Management","Content Management",Templates}', '{English, German, French, Spanish, Italian, Japanese, Portuguese, Dutch, Swedish, Finnish, Polish}', NULL, 'Office 365 Subscription', 'Basic, Standard, Premium, Enterprise plans', 'https://www.microsoft.com/en-us/microsoft-365/business/compare-all-microsoft-365-business-products', 0, 'user'),
                ('salesforce-user', 'Salesforce (User)', 'Analyze your Salesforce data and discover their confidence score with CustomerCity', 'https://cdn-icons-png.flaticon.com/128/5968/5968914.png', 'CustomerCity', 'https://customercitydev.com', '10,000+', '{Marketing,CRM}', '{Analysis,Data,Confidence}', 'Japanese, German, Finnish, Swedish, Portuguese, English, Italian, French, Spanish, Polish, and Dutch', NULL, 'Salesforce Subscription', 'Essentials, Professional, Enterprise or Unlimited plans', 'https://www.salesforce.com/editions-pricing/overview/', 0, 'user');
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            DELETE FROM public.integration where application_id in (
                'google-calendar',
                'demandbase',
                'hubspot',
                'gmail',
                'marketo',
                'eloqua',
                'zoominfo',
                'apollo.io',
                'clearbit',
                'outreach',
                'salesloft',
                'freshworks',
                'stripe',
                'linkedin-sales-navigator',
                'ms-dynamics-365',
                'zoho-crm',
                'mysql', '
                'oracle-database',
                'snowflake',
                'gainsight',
                'intercom',
                'zendesk',
                'slack',
                'postgresql',
                'aws-dynamodb',
                'ms-sql-azure',
                'aws-s3',
                'chargebee',
                'microsoft-teams',
                'pipedrive',
                'xero',
                'salesforce-user'
            );  
        `);
  }
}
